### ISSUE TITLE
Return type from Feather.read

### ISSUE THREAD

**Issue by quinnj** [JuliaStats/Feather.jl#10]
With the current native implementation, we're just returning a tuple like `(header, data, ctable)` from `Feather.read`, with `data` being a `Vector{Arrow.AbstractColumn}`. While the `Arrow.jl` package is cute, it currently doesn't provide much real functionality other than as a convenient format to convert feather files into. My plan is to work more on `Arrow.jl` long-term, but I think it might be a ways out from being a serious consideration for functionality.

I'd like to propose we re-structure the Feather package to be based on the `DataStreams` framework, providing appropriate `Sink` and `Source` types, while retaining the higher-level `Feather.read`/`Feather.write` methods. `Feather.read` would then return a `Data.Table`, which is a small wrapper around a `Vector{NullableArray}`. We would then provide easy conversion routines to/from DataFrames, similar to other DataStream packages (CSV, SQLite, ODBC).

The advantages are that it's a very easy change/update and it will provide a strong basis for providing interop methods with the other DataStreams packages (e.g. return the result of of an ODBC query directly as a feather file).

**Comment by dmbates** [comment]
In the `dmb/Cxx` branch I had defined a minimal `Reader` structure as
```julia
type Reader
    path::AbstractString
    tpt::CTablePt
    buf::IO
    columns::Vector{Column}
end
```
where a column is
```julia
type Column{T}
    values::AbstractVector{T}
    name::String
end
```

The `CTablePt` is a `Cxx.CppPtr` object for accessing the FlatBuffers table.  There are methods to convert to a `DataFrame`, extract individual columns, etc.

This structure is somewhat fragile because you need to keep the `Reader` object in scope if you want the columns to retain their values.  As soon as the `buf` field in the `Reader` is garbage collected you lose the contents of the columns.  Obviously this is not a good long-term solution but it was enough for me to use it.

I am not that familiar with the `DataStreams` framework.  It seems that a Feather format file needs to be available in its entirety to be usable, because the metadata is at the end of the file.  Would treating it as a stream lose some of the advantage of memory-mapping?  In other words, would the generality of a `DataStream` come with a petrformance hit?

By the way, it is not a good time to try to benchmark the `dmb/Cxx` branch because the `Cxx` package uses `pointer_to_string` excessively resulting in slowdown from the deprecated warnings.

**Comment by quinnj** [comment]
Alright, we now have a fully functioning native implementation that reads/writes DataFrames. Closed via 243d0dbef69f967c124fdff16f1b9389dd5548d1

**Comment by Flomastruk** [comment]
Not sure that this comment belongs to here, so I apologize in advance...
I was curious whether it is possible to change the form of Feather.read output in a straightforward way. Currently one gets a DataFrame filled with NullableArrays. I want to define alternative way to read .feather files to julia that would give DataArrays instead of NullableArrays. So in the heart of code in Feather.jl I replace the call to constructor of NullableArray:

```julia
arr = Feather.unwrap(convert(Ptr{typ}, pointer(m) + values.offset + bitmask_bytes), rows)
column = NullableArray{eltype(arr),1}(arr, nulls, parent)
```

by call to DataArray constructor:

```julia
arr = Feather.unwrap(convert(Ptr{typ}, pointer(m) + values.offset + bitmask_bytes), rows)
column = DataArray(arr, nulls)
```
It seems that it should fine. But after reading file and trying to access columns of a data frame I get the following error: 

```
signal (11): Segmentation fault: 11
alignment at show.jl:1014
print_matrix at show.jl:1114
print_matrix at show.jl:1081
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1691
anonymous at replutil.jl:23
with_output_limit at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
writemime at replutil.jl:23
jlcall_writemime_22231 at  (unknown line)
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1691
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia.h:1331
sprint at iostream.jl:206
julia_render_22230 at  (unknown line)
julia_render_22223 at  (unknown line)
....
```

Closer inspection shows that despite one gets nullable arrays without any problem, ordinary arrays or dataarrays read in a similar way cause same segmentation fault.
Any ideas what's going on?

Thanks!

**Comment by dmbates** [comment]
As I wrote above, the original design had a lightweight Feather.Reader type that provided the description of the data frame and memory-mapped contents of the columns and, if present, the bitmap for the missing values.  Feather provides an excellent opportunity to sidestep the whole issue of arrays with missing values as `NullableArrays` or as `DataArrays` because it records the number of missing values in a column as part of the column's metadata.  If that number is zero, as is frequently the case, then you can return a regular Julia  Array directly.

As time allows I will populate the `dmb/Reader` branch to revert to this deign.

**Comment by quinnj** [comment]
@dmbates, it was never clear to me how you actually could "use" a `Feather.Reader` though. How was I supposed to traverse the values in a column? How do I index a single cell value? All of those operations require dealing with something like NullableArrays/DataArrays, or at a minimum, a Nullable type. Otherwise, the type instability kills you.

That said, we could certainly return a regular Array in cases where the null_count is 0, but I just don't see any other way around getting a Feather file into some kind of Julia structure that you can actually use.

@Flomastruk, the issue there is that we need to keep references around to the memory-mapped file, otherwise the data is invalidated when you try ot use it. Right now, we pass `parent` to NullableArray, which keeps that reference and makes everything safe to use. If you want ot use a DataArray, you should be fine doing it the way you showed, you just need to keep a reference to the `parent` field as well.

**Comment by dmbates** [comment]
There was a `DataFrame` constructor that takes a `Feather.Reader`.  The point is that you lose information when you return a `DataFrame` directly and there is no cost in retaining the `Feather.Reader` object.

**Comment by quinnj** [comment]
I don't think that's any different then than the current `Feather.Source` type. It's basically the parsed feather metadata + memory map.
