### ISSUE TITLE
Field based streaming support in Sink

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/Feather.jl#16]
It seems that right now a feather sink needs a source that supports the column-based streaming protocol. Are there plans to also make it work with field-based sources?

**Comment by quinnj** [comment]
Currently it supports field-based streaming through a DataFrame intermediary. i.e. Feather.Sink is registered to support field-based streaming, and the implementation involves field-streaming the Source to a dataframe, then streaming it out to a Feather.Sink. As far as I can tell, it's about as efficient as any other approach due to the nature of the feather binary file format.

**Comment by davidanthoff** [comment]
Ah, it works with the master version, just not the latest tagged one!

I think with that I have complete support for DataStream sources and sinks in Query, i.e. you can query any DataStream source, and you can write the result of a Query into any DataStream sink.

I might have a couple of API suggestions down the road how we can make things smoother, but it will all be functional with my next push.

So I guess I'm just going to wait for the next tag :)
